server:
  port: 8085

spring:
  application:
    name: zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cty
    username: root
    password: 213316

eureka:
  client:
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:8080/eureka

#以/api-a/ 开头的请求都转发给service-ribbon服务；
#以/api-b/开头的请求都转发给service-feign服务；
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl